### ISSUE TITLE
Support for Command Aliases

### ISSUE THREAD

**Issue by Chris3606** [innot/argparseDecorator#4]
Currently, I can't find a way to create an alias for a command via the `@command` decorator.

In argparse, you can pass `aliases` to `add_parser` to provide aliases that resolve to the same subparser.  It would be useful if that was exposed; though I'm not sure if that has implications for the help system?

**Comment by innot** [comment]
Hi, 
it has been a while since I worked on that project, but it should not be too difficult to add something like:

```
@cli.command(aliases=["foo", "bar"])
def foobar(self, ....)
```

wrt to the help system I will have to check on how to best represent aliases.

I will look into this, stay tuned...

**Comment by Chris3606** [comment]
Thanks!  If there's anything I can do to help, please let me know.

**Comment by innot** [comment]
Well, that was easier than expected.

Commands can now have aliases (Syntax as above). Help was no problem, as argparse takes care of that - command aliases are shown in parenthesis when running help.

I have pulled the changes into the master branch. However I will take a look at your other issue before publishing a new version  to pypi.
